---
name: Release Installer ISO
on:
  release:
    types:
      - created

jobs:
  release_iso:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    strategy:
      matrix:
        flavor: ["main", "nvidia"]

    steps:
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Resolve Version and Tag
        id: versioning
        run: |
          case ${{ github.ref_name }} in 
            test*)
              echo "version=41" >> $GITHUB_OUTPUT
              echo "tag=dev" >> $GITHUB_OUTPUT
            ;;
            +[1-9]-*)
              $VERSION="${{ github.ref_name }}%%-"
              echo "version=$VERSION" >> $GITHUB_OUTPUT
              echo "tag=fedora-$VERSION" >> $GITHUB_OUTPUT
            ;;
            \*)
              exit -1
            ;;
          esac


      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          flatpak_remote_refs_dir: packages/flatpaks
          image_name: ${{ github.event.repository.name }}-${{ matrix.flavor }}
          image_repo: ghcr.io/${{ steps.registry_case.outputs.lowercase }}
          image_tag: ${{ steps.versioning.outputs.tag }}
          iso_name: ${{ github.event.repository.name }}-${{ matrix.flavor }}-${{ github.ref_name }}.iso
          variant: Xfce
          version: ${{ steps.versioning.outputs.version }}

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
